private var includedPrefixes:Array =
        [
            [
                "Rotten",
                "Broken",
                "Terrible",
                "Crappy",
                "Smelly",
                "Homely",
                "Disgusting",
                "Pathetic",
                "Not Recommended",
                "Feeble",
                "Wobbly",
                "Decrepit",
                "Misshapen",
                "Unseemly",
                "Unattractive",
                "Stoppable",
                "Discouraging",
                "Used",
                "Recycled",
                "Moldy",
                "Embarrassing",
                "Inefficient",
                "Lumpy",
                "Awkward",
                "Unsanitary",
                "Ill-conceived",
                "Rusty"
            ],
            [
                "Normal",
                "Temperamental",
                "Common",
                "Average",
                "Standard Issue",
                "Kid-Friendly",
                "Mother-Approved",
                "Safe",
                "Dull",
                "Plastic",
                "Run of the Mill",
                "Basic",
                "Fickle",
                "Sensitive",
                "Simple",
                "Ordinary",
                "Mediocre",
                "Plain",
                "Tasteful"
            ],
            [
                "Good",
                "Special",
                "Acceptable",
                "Appealing",
                "Attractive",
                "Pleasant",
                "Sufficient",
                "Above Average",
                "Efficient",
                "Encouraging",
                "Strong",
                "Benevolent",
                "Nice",
                "Capable",
                "Adequate"
            ],
            [
                "Soul Crushing",
                "Unstoppable",
                "Apocalyptic",
                "The Ender",
                "Super Shiny",
                "Celestial",
                "Incredible",
                "Masterful",
                "Astonishing",
                "Mind Blowing",
                "Head Splitting",
                "Sun Shaking",
                "Moon Melting",
                "Star Striking",
                "Meteor Mashing",
                "Demon Born"
            ]
        ];